### ISSUE TITLE
Elastic Stack Alpha Release

### ISSUE THREAD

**Issue by dougburks** [Security-Onion-Solutions/security-onion#1095]
- [x] Elasticsearch
  - [x] Docker container
  - [x] run as a non-root user
  - [x] log to /var/log/elasticsearch/
  - [x] add script to reset Elasticsearch database
  - [x] `--env "bootstrap_memory_lock=true"`
  - [x] `--ulimit memlock=-1:-1`
  - [x] `--env ES_JAVA_OPTS="-Xms$ELASTICSEARCH_HEAP -Xmx$ELASTICSEARCH_HEAP"`
  - [x] set initial `$ELASTICSEARCH_HEAP` based on available RAM
  - [x] `MAX_OPEN_FILES=65536`
  - [x] `elasticsearch - nofile 65536`
  - [x] `elasticsearch soft/hard nproc 2048`
  - [x] field [include_in_all] is deprecated, as [_all] is deprecated, and will be disallowed in 6.0, use [copy_to] instead.
- [x] Kibana
  - [x] Docker container
  - [x] run as a non-root user
  - [x] log to /var/log/kibana/
  - [x] set source_ip and destination_ip fields to type "ip"
  - [x] dashboard for each Bro log
  - [x] resolve `field type conflict` for `status_code` field
  - [x] remove ELSA shortcut from desktop and replace with Kibana
  - [x] Top Source/Destination by Total Bytes
  - [x] add source port to NIDS dashboard
  - [x] configure Kibana index for 1 shard and 0 replicas
  - [x] Indicator dashboard should only search last 24 hours by default
  - [x] Tables should show at least 10 results (perhaps 100)
  - [x] add visualizations and dashboard for Bro syslog.log
  - [x] add visualizations and dashboard for standard syslog coming from syslog-ng
  - [x] DNS dashboard needs to be adjusted for recent navigation menu change (scroll bar)
  - [x] comment out unnecessary config in /etc/kibana/kibana.yml
  - [x] build new Kibana image with links to Squert and Logout in the side bar
  - [x] add message visualization to Notices dashboard
  - [x] add sub_message visualization to Notices dashboard
  - [x] DNS query field should hyperlink to Indicator dashboard
  - [x] SSL Server Name field should hyperlink to Indicator dashboard
  - [x] remove Squert and Logout links from Navigation visualization in favor of new links in side bar
  - [x] HTTP site (virtual_host) field should hyperlink to Indicator dashboard
  - [x] Intel indicator field should hyperlink to Indicator dashboard
  - [x] Bro Files - Source IP field should hyperlink to Indicator dashboard
  - [x] move ElastAlert menu entry from Other to Alert Data
  - [x] add dashboard for ElastAlert
  - [x] fix index-pattern-field(s) for Sysmon
  - [x] fix index-pattern-field(s) for Autoruns
  - [x] source_port field should hyperlink to Indicator dashboard
  - [x] destination_port field should hyperlink to Indicator dashboard
  - [x] set timepicker:timeDefaults to search last 24 hours
  - [x] set dashboard:defaultDarkTheme to true
  - [x] Bro Connections maps are showing a scroll bar for the navigation menu, needs resizing
  - [x] Firewall dashboard has multiple "could not locate that index-pattern-field" errors
  
- [x] Logstash
  - [x] Docker container
  - [x] run as a non-root user
  - [x] log to /var/log/logstash/
  - [x] fix typo in filename `0001_intput_json.conf`
  - [x] add filters for bro_modbus, bro_pe, bro_rfb, bro_sip, bro_radius, bro_dnp3
  - [x] change event to event.set and event.get where necessary
  - [x] only add `bro` tag if type is `bro`
  - [x] move `rename` from 0000_input to 1000_preprocess
  - [x] comment out 0003_input_syslog.conf
  - [x] update Bro patterns for Bro 2.5 (https://github.com/Security-Onion-Solutions/security-onion/issues/1029)
  - [x] add parser for OSSEC alerts
  - [x] add parsers for Bro SMB
  - [x] parse Bro Notice fields `message` and `sub_message` as `msg` and `sub_msg` 
  - [x] retain IPv6 addresses
  - [x] add logstash_time field
  - [x] persistent queues
  - [x] set `pipeline.workers: 1`
  - [x] NIDS alert - lookup rule in /etc/nsm/rules/ and insert into alert
  - [x] parse pfSense firewall logs
  - [x] parse Sysmon logs
  - [x] parse Autoruns logs
  - [x] rebuild logstash image with [new logstash-filter-rest plugin](https://github.com/lucashenning/logstash-filter-rest/issues/27#issuecomment-318887442)
  - [x] update pfSense parser with [fix for grokparsefailure on ICMPv6 traffic](https://groups.google.com/d/topic/security-onion-testing/NJmTTL4e49g/discussion)
  - [x] update Snort parser to parse [sensor name](https://github.com/Security-Onion-Solutions/security-onion/issues/652)
- [x] Curator
  - [x] Docker container
  - [x] run as a non-root user
  - [x] log to /var/log/curator/
- [x] ElastAlert
  - [x] Docker container
  - [x] run as a non-root user
  - [x] log to /var/log/elastalert/
  - [x] disable elasticsearch replicas for elastalert_status and reduce shards to 1
  - [x] default rules should use `use_count_query`
- [x] Freqserver
  - [x] Docker container
  - [x] run as a non-root user

- [x] Domainstats
  - [x] Docker container
  - [x] run as a non-root user

- [x] so-elastic-configure
  - [x] check for options in /etc/nsm/securityonion.conf before adding them
- [x] so-elastic-configure-elastalert
  - [x] check to see if `elastalert_status` index exists before deleting
- [x] so-elastic-start
  - [x] `--link` is a deprecated legacy feature, replace with user-defined network
  - [x] need a timeout value when [checking for Elasticsearch so that script doesn't hang forever](https://github.com/Security-Onion-Solutions/elastic-test/blob/master/usr/sbin/so-elastic-start#L98)
  - [x] provide prettier/quieter message when container(s) already started
- [x] so-start / so-stop / so-restart
  - [x] create small wrapper scripts that control both NSM and Elastic
  - [x] create /usr/sbin/so-status
- [x] sostat
  - [x] provide stats for Elastic stack
- [x] soup
  - [x] when docker is upgraded, it stops all containers, need to restart
- [x] ELSA
  - [x] dump ELSA data out to filesystem in a form that Logstash can read
  - [x] have Logstash read the original Bro timestamp and use that for ingestion into ES

- [x] CapMe
  - [x] move to single sign-on
  - [x] update for cross cluster search
- [x] Sguil
  - [x] change ELSA pivot to Kibana search for that IP on Indicator dashboard

- [x] Squert
  - [x] pivot from IP address to Kibana search for that IP on Indicator dashboard
  - [x] move to single sign-on

- [x] Setup
  - [x] add Elastic option to Setup for new installations but mark it `Experimental`
  - [x] exclude docker interfaces from interface selection
- [x] OSSEC
  - [x] rootcheck is alerting on `Files hidden inside directory '/var/lib/docker/aufs`
  - [x] opening multiple kibana tabs may result in active response "High amount of POST requests in a small period of time (likely bot)", check for /es_admin
- [x] distributed deployments
  - [x] [Cross Cluster Search](https://www.elastic.co/guide/en/elasticsearch/reference/5.5/modules-cross-cluster-search.html)
- [x] update existing packages
    - [x] securityonion-setup
    - [x] securityonion-sostat
- [x] build new packages where necessary
    - [x] securityonion-elastic
    - [x] securityonion-samples-bro
- [x] develop tests for QA
  - [x] check for _grokparsefailure, _csvparsefailure, _rubyexception
  - [x] check log files:
    - /var/log/elasticsearch/
    - /var/log/logstash/
    - /var/log/kibana/
    - /var/log/elastalert/
    - /var/log/curator/
    - /var/log/freqserver/
    - /var/log/apache2/*

**Comment by JonZeolla** [comment]
Not sure if it's helpful, but not too long back I put together [a wiki article](https://cwiki.apache.org/confluence/display/METRON/Tuning+the+Search+tier) covering how to tune ES, focused on bro data for another project.  It is intended for 2.4, and I noticed you recently upgraded to 5.4, so I'm not sure if this is still valid.

**Comment by dougburks** [comment]
Thanks @JonZeolla !

**Comment by ragdelaed** [comment]
are there any plans for a hadoop/big data enabled back end for SO? 
or do you plan to use kafka, storm, zeppelin or any other tools from the hadoop ecosystem? 
also any profiling, baseling, or anything like that for statistical or machine learning analysis?
and do you plan to pull in windows event logs in the future in addition to bro/snort/etc?

thanks for your work on this, its an excellent product, elegant, and it fits in my brain nicely. :)

**Comment by dougburks** [comment]
Hi @ragdelaed ,

You can pull in Windows Event Logs today using OSSEC agent or several other event log collectors.

Right now, our main focus is integrating the Elastic stack.  Once that is done, we'll look at what makes the most sense for our next project.

Thanks!

**Comment by mv003348** [comment]
@dougburks - This migration is AWESOME. I have already taken version one if your script and turned it into a fully functioning AWS AMI. As a proof of concept 1:1 ratio (management to sniffing interface), I have collected data to show my teams what type of traffic is coming into our system.  I have begun to play around with ElastAlert, but running into some index pattern issues.  I have showed this off to my teams enough times that once the migration to ELK is completed, we are going to be implementing this across the entire company. All I can say is JOB WELL DONE SIR and THANK YOU!

FYI - I am hoping to be at the Security Onion conference this year. Very excited!

**Comment by dougburks** [comment]
Hi @mv003348 ,

Thanks for the feedback!  Hope to see you at the conference!

**Comment by gaganova** [comment]
Is this transition to elastic stack something that will definitely happen? Why? I would be very interested in reading about your reasons for this decision. Don't you think ES is too much bloat?

**Comment by dougburks** [comment]
Hi @gaganova ,

This is most likely going to happen.  Our community and our customers have been asking for the Elastic Stack for quite some time and we try to be responsive to demand.

**Comment by gaganova** [comment]
I am asking myself if people demand that because they have only seen nice ELK screenshots or if they have actually used that bloated java stack in real life. Of course there is no answer to that, so hopefully this project will survive this decision. Good Luck! Anybody interested in maintaining the ELSA based version with 16.04?

**Comment by dougburks** [comment]
Hi @gaganova ,

Replies inline.

> I am asking myself if people demand that because they have only seen nice ELK screenshots or if they have actually used that bloated java stack in real life. Of course there is no answer to that, so hopefully this project will survive this decision. Good Luck!

I can tell you that there are many folks in our community who have already rolled their own Elastic deployment and are quite happy with it.

> Anybody interested in maintaining the ELSA based version with 16.04?

While ELSA certainly has low resource requirements, that results in quite a few drawbacks which limit hunting capabilities (only 12 indexed fields, no multiple groupby, just to name a few).  These limitations caused the lead developer of ELSA to then migrate to Elasticsearch for what was going to be ELSA 2.0.  The future of ELSA 2.0 is currently unclear, thus we are moving to the Elastic stack.

**Comment by mattraneri** [comment]
Hi @dougburks,

First and foremost, love this project.  I would love to add the ELK stack to my deployment, but is there a timeline of when it will officially be supported?  I'd hate to implement this in our deployment and have the official project roll out ELK two weeks later.  Just asking because the last blog post was all I  was able to find  directly referencing the script, which is now months old.

Thank you!

**Comment by dougburks** [comment]
Hi @mattraneri ,

We've had a few blog posts about the Elastic integration:
http://blog.securityonion.net/search/label/elastic

We're not ready to commit to any timelines at this point.  This is a large project and we still have a lot of work left to do.  This is an important project and we want to make sure that it's done right!

Thanks!

**Comment by mv003348** [comment]
@dougburks - I have been following the updates and launching new EC2 instances every time a new TP comes out. All I can say is, :mind blown:. This stuff is AWESOME! Whenever it becomes a stable version, I am making it our Enterprise IDS tool...all I need now are boat loads of SO stickers!  THANK YOU!

**Comment by kxuanCeltik** [comment]
Hi @dougburks,

Congratulations, this integration is awesome.

Where are the dockerfiles o how manage the containers? How is the deployment ?

THANKS !!!

**Comment by kxuanCeltik** [comment]
Sorry I've already found docker images.

But I try config with Production Mode and I have problems with dockers.

I would like test  the integration to do an academic work, 
maybe, Could I open other issues?

**Comment by weslambert** [comment]
@kxuanCeltik ,

Please see: http://blog.securityonion.net/2017/07/towards-elastic-on-security-onion.html

This technology preview only works with **Evaluation Mode** currently.

Instead of opening an issue, or commenting on this issue, please use our mailing list:

https://github.com/Security-Onion-Solutions/security-onion/wiki/MailingLists#security-onionv

Also see: https://groups.google.com/forum/#!topic/security-onion/Sr8wrJSQxo0

Thanks,
Wes

**Comment by kxuanCeltik** [comment]
Ok, thanks.

**Comment by Behkxyz** [comment]
@dougburks just to add some notes https://groups.google.com/forum/#!topic/security-onion/-PDV2E8Jn6k that resolves the massive amount of _grokparsefailure for the NIDS, I've not seen another log like that after the correction, not sure if related to the TODO "check for _grokparsefailure" thing.

**Comment by dougburks** [comment]
Hi @Behkxyz ,

Yes, the fix in that google group thread was already in our dev repo and so it will automatically go into the next release.  As we announce future releases, please continue to watch out for _grokparsefailures and report them on the mailing list so they can be resolved.

Thanks!

**Comment by dougburks** [comment]
submitted to QA group for testing:
https://groups.google.com/d/topic/security-onion-testing/Nn3jWvxhqk0/discussion

**Comment by dougburks** [comment]
published:
http://blog.securityonion.net/2017/09/elastic-stack-alpha-release-and.html
